definitions:
  models.OrganizationDB:
    properties:
      about:
        type: string
      color:
        items:
          type: string
        type: array
      created_at:
        type: string
      email:
        type: string
      employees_amount:
        type: integer
      full_name:
        $ref: '#/definitions/sql.NullString'
      gr_points:
        type: integer
      id:
        type: integer
      logo:
        type: string
      name:
        type: string
      organization_inn:
        type: string
      phone:
        type: string
      revenue:
        type: integer
      status:
        type: string
      updated_at:
        type: string
      url:
        type: string
    type: object
  sql.NullString:
    properties:
      string:
        type: string
      valid:
        description: Valid is true if String is not NULL
        type: boolean
    type: object
info:
  version: "1.0"
  title: "Go Organizations maps"
  contact: {}
paths:
  /api/organizations/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.OrganizationDB'
            type: array
swagger: "2.0"
